name: Data Update

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run data update script
        run: node ./data-source/fetch-and-compute.js
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Create Pull Request if changes exist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Create a new branch with timestamp
          BRANCH_NAME="data-update/$(date +%Y-%m-%d-%H-%M-%S)"
          git checkout -b $BRANCH_NAME
          
          git add .
          
          # Only proceed if there are changes
          if ! git diff --quiet HEAD; then
            git commit -m "chore: update computed data files"
            git push origin $BRANCH_NAME
            
            # Create Pull Request using GitHub CLI
            gh pr create \
              --title "Data Update $(date +%Y-%m-%d)" \
              --body "Automated data update from GitHub Actions" \
              --base main \
              --head $BRANCH_NAME
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 