name: Fetch all data and compute sahm rule

on:
  schedule:
    - cron: "0 0 1-7 * 5" # Runs at midnight UTC on the first Friday of every month
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-map-data:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run data update script
        run: node ./data-source/fetch-and-compute.js
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Upload modified files (fetch-map-data)
        uses: actions/upload-artifact@v4
        with:
          name: fetch-map-data-files
          path: . # You can specify more specific paths if needed

  fetch-tool-data:
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: rocker/tidyverse:latest # Use the official tidyverse image
      options: --user root # Optional: ensure the user has root access for installing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install additional R packages
        run: |
          R -e "install.packages(c('fredr', 'lubridate'))"
        env:
          R_LIBS_USER: ${{ runner.temp }}/Library

      - name: Run FRED data fetch script
        run: Rscript data-source/fetch_files.R
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Upload modified files (fetch-tool-data)
        uses: actions/upload-artifact@v4
        with:
          name: fetch-tool-data-files
          path: . # You can specify more specific paths if needed

  commit:
    runs-on: ubuntu-latest
    environment: github-pages
    needs: [fetch-map-data, fetch-tool-data] # Ensure this job waits for both previous jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download files from fetch-map-data
        uses: actions/download-artifact@v4
        with:
          name: fetch-map-data-files

      - name: Download files from fetch-tool-data
        uses: actions/download-artifact@v4
        with:
          name: fetch-tool-data-files

      - name: Commit and push all changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Stage all changes from both fetch-map-data and fetch-tool-data jobs
          git add .  # Stage all changes

          # Check if there are any changes to commit
          git diff --cached --quiet || (
            git commit -m "chore: update computed data files from map and tool data" && 
            git pull --rebase && 
            git push
          )
