name: Fetch all data and compute sahm rule

on:
  schedule:
    - cron: '0 0 1-7 * 5'  # Runs at midnight UTC on the first Friday of every month
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-all-data:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger fetch-tool-data.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: fetch-tool-data.yml
          ref: ${{ github.ref }}
      
      - name: Trigger fetch-map-data.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: fetch-map-data.yml
          ref: ${{ github.ref }}