name: Fetch FRED Data (R script)

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: rocker/tidyverse:latest  # Use the official tidyverse image
      options: --user root  # Optional: ensure the user has root access for installing packages

    steps:
    - uses: actions/checkout@v3

    - name: Install additional R packages
      run: |
        R -e "install.packages(c('fredr', 'lubridate'))"
      env:
        R_LIBS_USER: ${{ runner.temp }}/Library

    - name: Run FRED data fetch script
      run: Rscript data-source/fetch_files.R
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
