name: Fetch FRED Data (R script)

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    environment: github-pages

    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Cache R packages
      uses: actions/cache@v3
      with:
        path: ${{ runner.temp }}/Library
        key: r-lib-${{ runner.os }}-${{ hashFiles('**/*.R', '**/*.Rmd', '**/*.Rproj') }}
        restore-keys: |
          r-lib-${{ runner.os }}-

    - name: Create user library directory
      run: mkdir -p $R_LIBS_USER
      env:
        R_LIBS_USER: ${{ runner.temp }}/Library

    - name: Install R packages
      run: |
        set -e
        Rscript -e 'install.packages(c("httr", "jsonlite", "dplyr", "fredr", "tidyverse", "lubridate"), repos="https://cloud.r-project.org", dependencies=TRUE)'
      env:
        R_LIBS_USER: ${{ runner.temp }}/Library

    - name: Run FRED data fetch script
      run: Rscript data-source/fetch_files.R
      env:
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        R_LIBS_USER: ${{ runner.temp }}/Library
