name: Fetch counties data from FRED api

on:
  workflow_dispatch:       # Allows manual trigger

jobs:
  fetch-counties-data:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run data update script
        run: node ./data-source/fetch-and-compute.js
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}