name: Fetch FRED Data

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("fredr", "tidyverse", "lubridate"), repos="https://cloud.r-project.org")'

    - name: Run FRED data fetch script
      run: Rscript data-source/fetch_files.R

    - name: Commit and push if changes exist
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update FRED data" && git push) 