name: Fetch data fro FRED api for interactive tool

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    environment: github-pages
    container:
      image: rocker/tidyverse:latest  # Use the official tidyverse image
      options: --user root  # Optional: ensure the user has root access for installing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install additional R packages
        run: |
          R -e "install.packages(c('fredr', 'lubridate'))"
        env:
          R_LIBS_USER: ${{ runner.temp }}/Library

      - name: Run FRED data fetch script
        run: Rscript data-source/fetch_files.R
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .  # Stage all changes
          git diff --cached --quiet || (git commit -m "chore: update data for interactive tool" && git pull --rebase && git push)

      - name: Trigger Webpage Deployment Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: webpage-deployment.yaml
          ref: ${{ github.ref }}
